apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gs
  name: gs
  namespace: sathvi
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gs
    spec:
      containers:
      - image: neelima640/abc:latest
        name: abc
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-03-27T10:41:41Z"
  name: gssvc
  namespace: sathvi
   
  
spec:
  ports:
    -  port: 8080
       protocol: TCP
       targetPort: 8080
  selector:
    app: gs
  
  type: NodePort

