name: cicd-pipeline

on: 
  workflow_dispatch:

jobs:
  clone:
    runs-on: self-hosted
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
    - name: Clone-source
      run: |
        git clone https://github.com/NeelimaNeeli/DevOps-K8s-Security.git

  build:
    runs-on: self-hosted
    needs: code_analysis
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
    - name: Build with Maven
      #working-directory: DevOps-K8s-Security  # Enter the directory where your Maven project is located
      run: mvn clean package
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: DevOps-K8s-Security/target

  code_analysis:
    runs-on: self-hosted
    needs: clone
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2 
    - name: Build and analyze
      #working-directory: DevOps-K8s-Security  # Enter the directory where your Maven project is located
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=github-actions -Dsonar.projectName='github-actions'

  accessing_tomcat:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
    
    - name: Build Docker image
      working-directory: DevOps-K8s-Security  # Ensure the correct directory
      run: docker build -t myapp .
