name: cicd-pipeline

on: 
  workflow_dispatch:

jobs:
  clone:
    runs-on: self-hosted
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
    - name: Clone-source
      run: |
        git clone https://github.com/NeelimaNeeli/DevOps-K8s-Security.git

  build:
    runs-on: self-hosted
    needs: clone
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      working-directory: DevOps-K8s-Security  # Enter the directory where your Maven project is located
      run: mvn clean package
    
